/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactId = IDL.Nat;
export const ServiceInterest = IDL.Variant({
  'accessories' : IDL.Null,
  'other' : IDL.Null,
  'cloud' : IDL.Null,
  'networking' : IDL.Null,
  'computers' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactInquiryInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getContactInquiry' : IDL.Func([ContactId], [IDL.Opt(ContactInquiry)], []),
  'listContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], []),
  'submitContactInquiry' : IDL.Func([ContactInquiryInput], [ContactId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactId = IDL.Nat;
  const ServiceInterest = IDL.Variant({
    'accessories' : IDL.Null,
    'other' : IDL.Null,
    'cloud' : IDL.Null,
    'networking' : IDL.Null,
    'computers' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactInquiryInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getContactInquiry' : IDL.Func([ContactId], [IDL.Opt(ContactInquiry)], []),
    'listContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], []),
    'submitContactInquiry' : IDL.Func([ContactInquiryInput], [ContactId], []),
  });
};

export const init = ({ IDL }) => { return []; };